README.md
Added more precise information about format of registeration number to be inputted and Successfully sent the PR
=> Update the Readme.md file

.gitignore, views/account/login.hbs, views/account/o/login.hbs, views/account/register.hbs, views/account/register/verify.hbs, views/dashboard/dashboard.hbs, views/dashboard/data.hbs, views/dashboard/dev.hbs, views/dashboard/profile.hbs, views/error.hbs, views/landing.hbs, views/password/request.hbs, views/password/reset.hbs, views/profile/homepage.hbs
fixes #20 
Clipboard icons are added to the UI.
Favicon added
=> copy to clipboard icon added

views/dashboard/dev.hbs
Issue fixed:- https://github.com/UniAuth/uniauth-backend/issues/26
fixes #26
=> `/dashboard/dev` layout issues

views/dashboard/dev.hbs
Issue fixed:- https://github.com/UniAuth/uniauth-backend/issues/27
=> copy to clipboard not working #27 fixed

.github/workflows/doc.yml, README.md, package.json
Issue solved: https://github.com/UniAuth/uniauth-backend/issues/10
=> deployed docs on Github pages

src/application/application.service.ts, src/dashboard/dashboard.controller.ts, views/dashboard/data.hbs
=> List of  applications having access to user data.

views/account/login.hbs, views/account/register.hbs
=> add password validation

README.md
=> docs(readme): update screenshots

README.md, src/user/user.schema.ts, views/dashboard/dev.hbs
=> JS Error while creating new applicaiton  fix

config/default.yml, src/mailer/constants/confirmEmailToken.constants.ts, src/mailer/mailer.controller.spec.ts, src/mailer/mailer.controller.ts, src/mailer/mailer.module.ts, src/mailer/mailer.service.spec.ts, src/mailer/mailer.service.ts
=> E-mail module implemented. This fixes issue #43

README.md
=> docs(readme): remove travic-ci badge

views/password/reset.hbs
=> fix(ui): hide passwd input field in passwd reset

views/password/reset.hbs
=> feat(passwd reset): compare passwd before reset

views/password/request.hbs
=> fix(passwd reset): share email via form data

src/dashboard/dashboard.controller.spec.ts
=> test(dashboard): controller setup

src/dashboard/dashboard.service.spec.ts
=> test(dashboard): add test for service

src/mailer/mailer.service.spec.ts
Fixes #65 
Screen Shot of test
=> feat(mailer): add tests for service

src/account/account.service.spec.ts
Fixes #64 
Screen Shot of the test
=> test(account): add tests for service

src/application/application.service.spec.ts
Fixes #66 
Screen Shot of the test
=> test(application): add test for service

src/account/account.controller.spec.ts
Fixes #42 
Screen Shot for test
=> feat(account): add test for controller

src/auth/auth.service.spec.ts
Fixes #68 
Screen Shot for test
=> test(auth): add tests for service

src/application/application.controller.spec.ts
Fixes #41 
Screen Shot of the test
=> test(application): add tests for controller

README.md
=> docs(readme): add steps to get sendgrid API

src/user/user.service.spec.ts
=> test(user): fix service test failing

src/main.ts
=> fix(app): server crash on load

views/password/reset.hbs
Fixes #102 
Bug: Form tag was missing which prevented the submission of the form.
=> fix(passwd reset): add length check

src/application/application.service.ts, src/dashboard/dashboard.controller.ts, views/dashboard/dev.hbs
=> feat(application): add delete feature

Dockerfile
=> chore(build): add dockerfile

views/account/register.hbs, views/password/reset.hbs
=> fix(passwd): update regex

views/dashboard/details.hbs, views/dashboard/dev.hbs
Fixes #106 
Fixes Frontend part.
Screen Shot
=> feat(application): add ui to display user list

README.md, views/dashboard/dev.hbs
=> fix(ui): cards combining into single card

package.json
- fixes #63 
- Added pre commit hook
** Original SS ** | ** Updated SS**
=> chore(git): setup pre commit hook for lint and format

README.md, src/main.ts, views/dashboard/dashboard.hbs, views/dashboard/data.hbs, views/dashboard/details.hbs, views/dashboard/dev.hbs, views/dashboard/profile.hbs, views/partials/header.hbs
- fixes #107 
- Added partials to avoid code duplication
- any additional information
=> refactor(views): add partials to avoid code duplication

views/dashboard/dev.hbs
- fixes #124 
- Edited verification of status code from json to meta 
- Removed identical ids for multiple applications
** Original SS **
|
** Updated SS **
=> fix(application): error alert on creation

README.md, src/dashboard/dashboard.controller.ts, src/user/user.controller.ts, views/dashboard/profile.hbs, views/profile/edit.hbs
- fixes #69 , #71
- any additional information
=> chore(user): migrate route to application controller

src/account/account.controller.ts, views/partials/server-response.hbs
- fixes #127 
- Add a general server response page
- Fixed redirect routes after form submission for password reset request and password reset
=> fix(passwd): re-routing pages

.github/workflows/workflow.yml, test/jest-e2e.json
- fixes #120 
link to sample repo:
https://github.com/MASTERCHIEF011/codecov-node
=> chore(ci): integrated codecov coverage

src/application/application.service.ts, src/dashboard/dashboard.controller.ts
- fixes #108 
Count before deleting the application
Count after deleting the application
=> fixX(application): fix application count

views/dashboard/dev.hbs
=> fix(ui): onclick copy to clipboard function

views/dashboard/dev.hbs
- fixes #138 
- Added confirmation before deleting app
=> feat(ui): add confirmation before delete feature

views/dashboard/dev.hbs
=> feat(ui): add box shadow to app cards

src/user/user.controller.ts
=> chore(app): remove unused functions

config/appData.ts, config/default.yml, src/account/account.controller.ts, src/app.controller.ts, src/dashboard/dashboard.controller.ts, views/account/login.hbs, views/account/register.hbs, views/landing.hbs, views/partials/header.hbs, views/partials/server-response.hbs, views/password/request.hbs, views/password/reset.hbs, views/profile/edit.hbs
=> feat(app): customize from single file

src/account/account.controller.ts, src/account/account.service.spec.ts, src/app.module.ts, src/application/application.controller.ts, src/application/application.schema.ts, src/application/application.service.spec.ts, src/application/application.service.ts, src/application/dto/create-application.dto.ts, src/auth/auth.service.spec.ts, src/auth/auth.service.ts, src/auxiliary/exceptions/mongo.exceptions.ts, src/config/mongoose.config.ts, src/dashboard/dashboard.controller.ts, src/dashboard/dashboard.service.ts, src/mailer/mailer.module.ts, src/mailer/mailer.service.spec.ts, src/mailer/mailer.service.ts, src/main.ts, src/user/user.repository.ts, src/user/user.schema.ts, src/user/user.service.spec.ts, src/user/user.service.ts
=> Fixed all linting issues 

docker-compose.yml
=> compose file added

src/dashboard/dashboard.controller.ts, src/user/user.controller.spec.ts
- fixes #147 
- Removed function that no longer exists inside user controller
=> tests(user): eliminate outdated test

src/application/application.service.ts
- fixes #166 
- Fixed findAllByParticipant in application.service.ts
- none
=> fix(app): fixed findAllByParticipants method

views/dashboard/profile.hbs
- fixes #161 
- displayed the user details in a card format
- improved the edit button.
**Updated**
=> feat(ui): add card for user profile

src/application/application.service.ts, views/dashboard/dev.hbs
- Fix placement of delete button 
- Fixes #167 
- Aligned the delete buttons
** Original SS ** | ** Updated SS ** 
|
=> fix(ui): delete button in application card

views/profile/edit.hbs
-Add Dashboard link to Edit Profile Page 
- Fixes #162 
- added the header
- included Dashboard link
** ![image](https://user-images.githubusercontent.com/67281382/111906563-113ec600-8a77-11eb-93a4-b1a651ed771f.png)
** | ** 
**
=> feat(ui): add navbar logo to edit profile page

src/application/application.service.ts, src/application/dto/create-application.dto.ts
- fixes #175 
- Removed the rule of 15 characters from the application description
- 
- none
=> fix(app): fixed minimum description condition

views/profile/edit.hbs
-Center card in Edit Profile Page #163 
- centered the card
- improved the UI/UX of the edit card.
** Original SS
** | ** Updated SS
**
=> fet(ui): redesign center card of profile edit page #163

views/dashboard/data.hbs
- fixes #172 
- Changed the way data was represented in `views/dashboard/data.hbs`
- any additional information
** Original SS ** | ** Updated SS **
=> feat(ui): add cards to represented in applications

package.json, src/account/account.controller.spec.ts, src/account/account.controller.ts, src/account/account.service.spec.ts, src/account/account.service.ts, src/app.module.ts, src/application/application.controller.spec.ts, src/application/application.controller.ts, src/application/application.module.ts, src/application/application.service.spec.ts, src/application/application.service.ts, src/auth/auth.module.ts, src/auth/auth.service.spec.ts, src/auth/auth.service.ts, src/dashboard/dashboard.controller.spec.ts, src/dashboard/dashboard.controller.ts, src/logger/LoggerConfig.ts, src/mailer/mailer.controller.spec.ts, src/mailer/mailer.module.ts, src/mailer/mailer.service.spec.ts, src/mailer/mailer.service.ts, src/main.ts, src/user/user.controller.spec.ts, src/user/user.module.ts, src/user/user.service.spec.ts, src/user/user.service.ts, test/app.e2e-spec.ts, yarn.lock
- fixes #165 
- Configured Winston logger to log into files
- Classified error logs onto a separate file
- None
=> chore(server): Logging to a file
